title: Keyboards HI Meetup
description: Saturday, July 6th 2024, 12:00PM - 3:00PM
show_downloads: false
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: #
social:
  type: Organization
gems:
  - jekyll-mentions