title: Keyboards HI Meetup 2023
description: Sunday December 17th 2023, 9:00AM - 2:00PM
show_downloads: false
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: #
social:
  type: Organization
gems:
  - jekyll-mentions